version: '3.1'

services:
  kafka0:
    image: zhigui/zigledger-kafka:x86_64-0.4.6
    restart: always
    hostname: kafka0
    network_mode: "host"
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_BROKER_ID: 0
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10000
      KAFKA_LOG_RETENTION_MS: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka0
